import './globals.css';
import { poppins } from './fonts';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Food Delivery Landing Page',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className}  antialiased`}>{children}</body>
    </html>
  );
}
